name: Build Images
"on":
  push:
    branches:
      - main
    tags:
      - v*
    paths:
      - cue/**
      - sources/**
      - '*.json'
      - .github/workflows/*.yaml
  pull_request: {}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2.1.3
        with:
          go-version: "1.16"
      - name: Check out repo code
        uses: actions/checkout@v2.3.4
      - name: Use latest Packer
        uses: hashicorp-contrib/setup-packer@v1
      - name: Fetch additional packages
        run: |-
          sudo apt-get update
          sudo apt-get install tree fdisk gdisk qemu-user-static libarchive-tools psmisc tar autoconf make
      - name: Get packer-build-arm plugin
        run: |-
          git clone https://github.com/mkaczanowski/packer-builder-arm plugin
          cd plugin
          go mod download
          go build
      - name: Build the image
        run: |-
          cp plugin/packer-builder-arm .
          sudo packer build raspios-desktop.json || true
          test -f raspios-desktop-2021-10-30-arm.img
          zip raspios-desktop-2021-10-30-arm.img.zip raspios-desktop-2021-10-30-arm.img
      - name: Build the image
        run: |-
          cp plugin/packer-builder-arm .
          sudo packer build raspios-lite.json || true
          test -f raspios-lite-2021-10-30-arm.img
          zip raspios-lite-2021-10-30-arm.img.zip raspios-lite-2021-10-30-arm.img
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
      - name: Create release
        id: create_release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Raspberry Pi OS USB Gadget ${{ steps.get_version.outputs.VERSION }}
          body: Raspberry Pi OS Lite & Desktop with USB OTG configuration.
          draft: true
          prerelease: false
      - name: Upload release asset
        if: startsWith(github.ref, 'refs/tags/v')
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: raspios-desktop-2021-10-30-arm.img.zip
          asset_name: raspios-desktop-2021-10-30-arm.img.zip
          asset_content_type: application/zip
      - name: Upload release asset
        if: startsWith(github.ref, 'refs/tags/v')
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: raspios-lite-2021-10-30-arm.img.zip
          asset_name: raspios-lite-2021-10-30-arm.img.zip
          asset_content_type: application/zip
      - name: Publish release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: StuYarrow/publish-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          id: ${{ steps.create_release.outputs.id }}
